import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./data/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        terminal: {
          bg: '#0d1117',
          surface: '#161b22',
          border: '#30363d',
          text: '#e6edf3',
          muted: '#8b949e',
          green: '#3fb950',
          blue: '#79c0ff',
          yellow: '#e3b341',
          purple: '#d2a8ff',
          orange: '#ffa657',
          red: '#ff7b72',
        },
        surface: '#13131b',
        'surface-dim': '#13131b',
        'surface-bright': '#393842',
        'surface-container-lowest': '#0d0d16',
        'surface-container-low': '#1b1b23',
        'surface-container': '#1f1f27',
        'surface-container-high': '#292932',
        'surface-container-highest': '#34343d',
        'on-surface': '#e4e1ed',
        'on-surface-variant': '#b9cacb',
        'inverse-surface': '#e4e1ed',
        'inverse-on-surface': '#302f39',
        outline: '#849495',
        'outline-variant': '#3a494b',
        'surface-tint': '#00dbe7',
        primary: '#e1fdff',
        'on-primary': '#00363a',
        'primary-container': '#00f2ff',
        'on-primary-container': '#006a71',
        'inverse-primary': '#00696f',
        secondary: '#ebb2ff',
        'on-secondary': '#520071',
        'secondary-container': '#ce5dff',
        'on-secondary-container': '#480064',
        tertiary: '#fff6e4',
        'on-tertiary': '#3a3000',
        'tertiary-container': '#ffd81d',
        'on-tertiary-container': '#715e00',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#74f5ff',
        'primary-fixed-dim': '#00dbe7',
        'on-primary-fixed': '#002022',
        'on-primary-fixed-variant': '#004f54',
        'secondary-fixed': '#f8d8ff',
        'secondary-fixed-dim': '#ebb2ff',
        'on-secondary-fixed': '#320047',
        'on-secondary-fixed-variant': '#74009f',
        'tertiary-fixed': '#ffe16d',
        'tertiary-fixed-dim': '#e9c400',
        'on-tertiary-fixed': '#221b00',
        'on-tertiary-fixed-variant': '#544600',
        background: '#13131b',
        'on-background': '#e4e1ed',
        'surface-variant': '#34343d',
        'space-void': '#050508',
        'nebula-blue': '#161B33',
        'terminal-green': '#4AF626',
        'warning-amber': '#FFD700',
        'error-red': '#FF3131',
      },
      fontFamily: {
        mono: ['var(--font-jetbrains-mono)'],
        'label-caps': ['var(--font-jetbrains-mono)', 'JetBrains Mono'],
        'code-sm': ['var(--font-jetbrains-mono)', 'JetBrains Mono'],
        'code-md': ['var(--font-jetbrains-mono)', 'JetBrains Mono'],
        'display-xl': ['var(--font-sora)', 'Sora'],
        'headline-lg': ['var(--font-sora)', 'Sora'],
        'headline-lg-mobile': ['var(--font-sora)', 'Sora'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.15em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'code-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'code-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      spacing: {
        unit: '4px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'container-max': '1200px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      animation: {
        blink: 'blink 1s step-end infinite',
      },
      keyframes: {
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        }
      }
    },
  },
  plugins: [],
};
export default config;
